theme: jekyll-theme-minimal

title: 양태환 기술 블로그
description: 쿠버네티스, eBPF, Java, Go, Python, 그리고 머신러닝에 대한 이야기

# URL 설정 (너 주소에 맞게 이미 잘됨)
url: "https://taehwanyang.github.io"

# 포스트 URL 규칙 ⭐
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/