theme: jekyll-theme-minimal

title: Taehwan Dev Blog
description: 쿠버네티스, eBPF, 그리고 머신러닝 이야기

url: "https://taehwanyang.github.io"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/